deployment:
  replicas: 3

service:
  port: 80

serviceAccount:
  create: true

ingress:
  create: false
  ingressClassName: traefik
  host: example.org
  tls: false
  path: /

quiethnImage: ghcr.io/okunix/quiethn:latest
quiethnUpdaterImage: ghcr.io/okunix/quiethn-updater:latest

quiethn:
  host: 0.0.0.0
  port: 80

redis:
  addr: redis:6379
  db: 0
  password: ""

updater:
  schedule: "* * * * *"
  ttlSecondsAfterFinished: 60
