services:
  quiethn-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiethn-web
    restart: unless-stopped
    networks:
      - quiethn_net
    ports:
      - 8080:80/tcp
    environment:
      HN_REDIS_ADDR: quiethn-valkey:6379
    depends_on:
      valkey:
        condition: service_healthy
  valkey:
    image: valkey/valkey:latest
    container_name: quiethn-valkey
    restart: unless-stopped
    ports:
      - 6379:6379/tcp
    volumes:
      - valkey_data:/data
      - ./valkey.conf:/etc/valkey/valkey.conf
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
    networks:
      - quiethn_net
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 10s
      retries: 3
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: quiethn-scheduler
    command: ["daemon", "--docker"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.quiethn-updater.command: "/bin/quiethn"
      ofelia.job-run.quiethn-updater.schedule: "0 * * * *"
      ofelia.job-run.quiethn-updater.network: "quiethn_net"
      ofelia.job-run.quiethn-updater.image: "ghcr.io/okunix/quiethn-updater:latest"
      ofelia.job-run.quiethn-updater.environment: '["HN_REDIS_ADDR=quiethn-valkey:6379"]'
    depends_on:
      valkey:
        condition: service_healthy

volumes:
  valkey_data: {}

networks:
  quiethn_net: {}
