{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quiethn.serviceAccountName" . }}
  labels:
    {{- include "quiethn.labels" . | nindent 4 }}
{{- end -}}
