apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quiethn.configMapName" . }}
  labels:
    {{- include "quiethn.labels" . | nindent 4 }}
data:
  serverPort: {{ .Values.quiethn.port }}
  serverHost: {{ .Values.quiethn.host }}
  redisAddr: {{ .Values.redis.addr }}
  redisDb: {{ .Values.redis.db | toString }}
  {{- with .Values.hackernewsBaseAddr }}
  hnAddr: {{ . }}
  {{- end }}
