apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quiethn.configMapName" . }}
  labels:
    {{- include "quiethn.labels" . | nindent 4 }}
data:
  redisAddr: {{ .Values.redis.addr }}
  redisDb: {{ default "0" .Values.redis.db | quote }}
  {{- with .Values.hackernewsBaseAddr }}
  hnAddr: {{ . }}
  {{- end }}
