apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quiethn.fullname" . }}
  labels:
    {{- include "quiethn.labels" . | nindent 4 }}
    app: {{ include "quiethn.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas }} 
  selector:
    matchLabels:
      app: {{ include "quiethn.fullname" . }}
  template:
    metadata:
      name: {{ include "quiethn.fullname" . }}
      labels:
        app: {{ include "quiethn.fullname" . }}
        {{- include "quiethn.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "quiethn.serviceAccountName" . }}
      containers:
        - image: {{ .Values.quiethnImage }}
          name: {{ include "quiethn.name" . }} 
          ports:
            - containerPort: {{ .Values.quiethn.port }}
              name: http
          env:
            {{- include "quiethn.env" . | nindent 12 }}
          livenessProbe:
            httpGet:
              port: {{ .Values.quiethn.port }}
              path: /
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: {{ .Values.quiethn.port }}
              path: /
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
