{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quiethn.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }} 
  rules:
  - host: {{ .Values.ingress.host }} 
    http:
      paths:
      - path: {{ .Values.ingress.path }} 
        pathType: Prefix
        backend:
          service:
            name: {{ include "quiethn.fullname" . }} 
            port:
              name: http
  {{- if .Values.ingress.tls }}
  tls:
    - hosts: {{ .Values.ingress.host }}
  {{- end }}
{{- end }}
